### ISSUE TITLE
GitLab runner us available from Homebrew as well

### ISSUE THREAD

**Issue by emartynov** [garrefa/automation-scripts#2]
You have a separate script for loading/updating it. However, you can modify your main script to have the option also install/update it from Homebrew.

**Comment by garrefa** [comment]
Thanks for the feedback.

I'm not sure how to check who is responsible for a homebrew formula. The reason I'm not using the homebrew installer is just that the documentation says: 
> In the future there will be a brew package, but for now you have to manually download the macOS binary.
So I'm not sure if it's an official thing.

I think I'll transform the script in modules so that I can call all of them from the main script but asking something like: Do you want to install X?. But for now, its separated so you can use the main script on your machine where you don't want gitlab-runner, you can run to install gitlab-runner in a machine where you already have your environment setup and you don't want to run the main script, and you can also run it to update the gitlab-runner in a machine that is already setup and with the runner.

**Comment by emartynov** [comment]
I think you're repeating homebrew. Maybe you can just create a list of packages that should be installed from Homebrew and then have a script that nicely installs or update every package?

Good Homebrew package also updates your bash configuration, so I would contribute to homebrew to fix packages that don't do it.

**Comment by garrefa** [comment]
Closing since we talked in person
